version: '3.1'

services:

  consignment-cli:
    build: ./consignment-cli

  consignment-service:
    build: ./consignment-service
    ports:
      - 50051:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:2017/"

  vessel-service:
    build: ./vessel-service
    ports:
      - 50052:50051
    environment:
      MICRO_ADDRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_HOST: "mongodb://datastore:2017/"

  datastore:
    image: mongo
    ports:
      - 27018:27017